---
- name: create rados gateway directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
  with_items:
    - /var/lib/ceph/radosgw
    - /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}
    - "{{ rbd_client_admin_socket_path }}"

- name: create rados gateway keyring
  command: '{{ lookup("template", "radosgw_create_keyring.j2") }}'
  args:
    creates: /etc/ceph/client.rgw.{{ ansible_hostname }}.keyring
  changed_when: false
  when: cephx
  delegate_to: '{{ groups[mon_group_name][0] }}'

- name: fetch rados gateway key
  fetch:
    src: /etc/ceph/client.rgw.{{ ansible_hostname }}.keyring
    dest: "{{ fetch_directory }}/{{ fsid }}/etc/ceph/client.rgw.{{ ansible_hostname }}.keyring"
    flat: yes
  when: cephx
  delegate_to: '{{ groups[mon_group_name][0] }}'

- name: put rados gateway key
  copy:
    src: "{{ fetch_directory }}/{{ fsid }}/etc/ceph/client.rgw.{{ ansible_hostname }}.keyring"
    dest: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/keyring
  when: cephx

- name: set rados gateway key permissions
  file:
    path: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/keyring
    owner: "ceph"
    group: "ceph"
    mode: "0600"
  when: cephx
