---
- name: check if rgw is started
  command: /etc/init.d/radosgw status
  register: rgwstatus
  changed_when: false
  failed_when: false
  check_mode: False

- name: start rgw
  service:
    name: ceph-radosgw@rgw.{{ ansible_hostname }}
    state: started
    enabled: yes
